FROM alpine
LABEL name="Nginx Server"
RUN apk update && apk upgrade \
&& apk add nginx 
RUN adduser -D -g 'www' www \
&& mkdir /www \
&& chown -R www:www /var/lib/nginx \
&& chown -R www:www /www
RUN mkdir -p /run/nginx
COPY ./index.html /www/
COPY ./nginx.conf /etc/nginx/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
